In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/raw/transactions_with_fraud.csv')
df

,transaction_id,user_id,timestamp,amount,merchant_name,merchant_category,latitude,longitude,city,country,card_last4,is_fraud,fraud_type,fraud_difficulty
0,TX0000162865,USER009705,2024-01-01 00:01:53,2487.11,Porto Sousa - ME,gas_station,28.373110,-70.266543,Cavalcanti de da Cunha,BR,9717,0,NaN,NaN
1,TX0000146243,USER002648,2024-01-01 00:04:38,160.91,Peixoto Pires - ME,utilities,-24.241923,22.937099,Correia da Prata,BR,6708,0,NaN,NaN
2,TX0000253392,USER004753,2024-01-01 00:05:05,311.60,Garcia,gas_station,68.745223,50.148051,Freitas,BR,7554,0,NaN,NaN
3,TX0000170578,USER004442,2024-01-01 00:06:40,169.52,Ribeiro - ME,gas_station,35.859043,-85.809268,Ramos,BR,5479,0,NaN,NaN
4,TX0000000370,USER011714,2024-01-01 00:06:45,78.60,Fernandes,pharmacy,24.261185,127.153616,da Mota,BR,8795,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300130,FRAUD_MERCHANT_EASY_0021,USER006837,2024-12-31 14:21:34,10394.70,Risky Merchant 2162,gambling,-38.537600,-51.553689,Foreign City,BZ,5840,1,risky_merchant,easy
300131,FRAUD_MERCHANT_HARD_0003,USER011899,2025-01-01 09:52:56,1144.43,Risky Merchant 1858,forex,77.229416,-94.611264,Cirino,BR,2247,1,risky_merchant,hard
300132,FRAUD_MERCHANT_EASY_0028,USER013674,2025-01-01 21:54:53,12518.59,Risky Merchant 8818,adult_content,-26.005729,-24.792901,Foreign City,MT,7984,1,risky_merchant,easy
300133,FRAUD_TIME_HARD_0007,USER008576,2025-01-02 01:02:21,884.60,Barbosa,restaurant,56.065428,-98.905644,Mendes de Pastor,BR,9093,1,unusual_time,hard
300134,FRAUD_MERCHANT_MEDIUM_0025,USER000170,2025-01-03 14:03:28,3059.15,Risky Merchant 8789,binary_options,-5.986184,-175.481651,Foreign City,HK,2122,1,risky_merchant,medium

In [5]:
# mostrar transacoes de um unico usuario
user_id = "USER009705"
df_user = df[df['user_id'] == user_id]
df_user

,transaction_id,user_id,timestamp,amount,merchant_name,merchant_category,latitude,longitude,city,country,card_last4,is_fraud,fraud_type,fraud_difficulty
0,TX0000162865,USER009705,2024-01-01 00:01:53,2487.11,Porto Sousa - ME,gas_station,28.373110,-70.266543,Cavalcanti de da Cunha,BR,9717,0,NaN,NaN
3672,TX0000190592,USER009705,2024-01-05 18:05:13,2112.67,Gomes Cavalcante - EI,pharmacy,28.300033,-70.357087,Cavalcanti de da Cunha,BR,7586,0,NaN,NaN
14707,TX0000266593,USER009705,2024-01-19 06:22:37,10000.00,da Cruz Nunes e Filhos,pharmacy,28.353935,-70.272736,Cavalcanti de da Cunha,BR,3563,0,NaN,NaN
20661,TX0000085747,USER009705,2024-01-26 12:46:56,3350.14,Castro,online_shopping,28.368909,-70.345461,Cavalcanti de da Cunha,BR,3590,0,NaN,NaN
20770,TX0000035551,USER009705,2024-01-26 13:50:21,2710.11,Machado Teixeira S/A,gas_station,28.405200,-70.338060,Cavalcanti de da Cunha,BR,2534,0,NaN,NaN
74741,TX0000271772,USER009705,2024-03-31 18:39:26,1349.66,LeÃ£o S/A,pharmacy,28.397812,-70.393613,Cavalcanti de da Cunha,BR,6528,0,NaN,NaN
89474,TX0000276600,USER009705,2024-04-18 18:46:03,2419.38,Porto,online_shopping,28.409234,-70.386694,Cavalcanti de da Cunha,BR,3618,0,NaN,NaN
91140,TX0000264317,USER009705,2024-04-20 19:14:53,3430.61,Cavalcanti,gas_station,28.404645,-70.287208,Cavalcanti de da Cunha,BR,4131,0,NaN,NaN
108213,TX0000032382,USER009705,2024-05-11 12:39:07,1218.36,Costela,grocery,28.332435,-70.235201,Cavalcanti de da Cunha,BR,9374,0,NaN,NaN
136851,TX0000180489,USER009705,2024-06-15 09:43:33,2378.37,CÃ¢mara,pharmacy,28.427742,-70.374560,Cavalcanti de da Cunha,BR,4143,0,NaN,NaN
165754,TX0000221949,USER009705,2024-07-20 13:57:55,2347.42,Rodrigues,pharmacy,28.282407,-70.278160,Cavalcanti de da Cunha,BR,7614,0,NaN,NaN
170942,TX0000130511,USER009705,2024-07-26 18:45:01,1125.10,Cavalcante,education,28.367846,-70.354487,Cavalcanti de da Cunha,BR,5326,0,NaN,NaN
182786,TX0000044248,USER009705,2024-08-09 21:37:02,1729.05,da Mata Pinto - ME,online_shopping,28.245803,-70.411562,Cavalcanti de da Cunha,BR,6667,0,NaN,NaN
187832,TX0000149135,USER009705,2024-08-16 13:13:26,2537.79,Andrade,clothing,28.275711,-70.329818,Cavalcanti de da Cunha,BR,5512,0,NaN,NaN
205534,TX0000135841,USER009705,2024-09-06 20:41:16,3677.75,Novaes,gas_station,28.323669,-70.235429,Cavalcanti de da Cunha,BR,2932,0,NaN,NaN
205791,TX0000173415,USER009705,2024-09-07 12:02:38,702.01,da Mota,pharmacy,28.374131,-70.358806,Cavalcanti de da Cunha,BR,3531,0,NaN,NaN
227703,TX0000019990,USER009705,2024-10-03 20:23:46,3467.47,Castro Dias Ltda.,utilities,28.395395,-70.296074,Cavalcanti de da Cunha,BR,9291,0,NaN,NaN
264208,TX0000251013,USER009705,2024-11-17 14:16:23,1619.04,Rios Siqueira Ltda.,pharmacy,28.376278,-70.308365,Cavalcanti de da Cunha,BR,7692,0,NaN,NaN
267638,TX0000223746,USER009705,2024-11-21 15:43:10,6990.45,Aparecida,pharmacy,28.434311,-70.289954,Cavalcanti de da Cunha,BR,9458,0,NaN,NaN
267764,TX0000014883,USER009705,2024-11-21 18:45:52,2226.31,Sousa,pharmacy,28.421459,-70.387144,Cavalcanti de da Cunha,BR,5995,0,NaN,NaN
273289,TX0000078672,USER009705,2024-11-28 13:51:15,1190.36,Montenegro Montenegro Ltda.,pharmacy,28.376523,-70.315123,Cavalcanti de da Cunha,BR,7300,0,NaN,NaN